version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./mainapp/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mainapp:/server
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DEBUG: 'True'
      DATABASE_URL: 'postgres://postgres:@db:5432/postgres'

  db:
    image: postgres:11.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres